### ISSUE TITLE
No siempre me gustan los macarrones

### ISSUE THREAD

**Issue by AlvareitorHD** [AlvareitorHD/pruebagit#1]
El codigo de ejemplo.cpp muestra siempre que me gustan los macarrones, pero no es siempre así; algunas veces también me gustan otras comidas, como las patatas o el pollo...

**Comment by Alux6** [comment]
Mi querido compañero Álvaro, entiendo su molestia sobre el caso de los gustos mezclados, pero no creo que pueda ayudarle, sin embargo puedo informarle de que lo que ha hecho usted es un issue y no una PR, por lo tanto no creo que fuese esto lo que usted pretendia, saludos.
